import Head from 'next/head'
import NavBar from "./navbar"

export default function Header() {
    return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/cbrex_icon.png" />
        </Head>
        <header>
            <NavBar />
        </header>
    </>
    )
}